2023-10-22 23:14:17.803 | INFO     | main:general_exception_handler:22 - dd
2023-10-22 23:16:03.844 | ERROR    | main:general_exception_handler:23 - Unexpected error occurred: (pymysql.err.ProgrammingError) (1146, "Table 'fastapi-demo.items' doesn't exist")
[SQL: SELECT items.id AS items_id, items.name AS items_name, items.description AS items_description 
FROM items 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'param_1': 0, 'param_2': 10}]
(Background on this error at: https://sqlalche.me/e/20/f405)
